name: compressed-size
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: compressed-size-action
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: '{wmr.cjs,demo/dist/**/*.{js,css,html}}'
          build-script: ci
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
