name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Change the condition for ESM Dist Test below when changing this.
        node-version: [12.18, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: cd packages/wmr && npm ci
      - name: Build
        run: cd packages/wmr && npm run build
      - name: Test
        run: ncd packages/wmr && pm test
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Prepare LHCI
        run: cd packages/wmr && npm install -g @lhci/cli@0.4.x
      - name: Install
        run: cd packages/wmr && npm ci
      - name: Build
        run: cd packages/wmr && npm run ci
      - name: LHCI
        run: cd packages/wmr && lhci autorun --upload.target=temporary-public-storage --collect.url="http://localhost:8080" --collect.startServerCommand="npm run demo:serve" --upload.githubAppToken=${{ secrets.LHCI_GITHUB_APP_TOKEN }}
