name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Change the condition for ESM Dist Test below when changing this.
        node-version: [12.18, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Build and Test
        run: npm test
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Prepare LHCI
        run: npm install -g @lhci/cli@0.4.x
      - name: LHCI
        run: lhci autorun --upload.target=temporary-public-storage --collect.url="http://localhost:8080" --collect.startServerCommand="npm run demo:serve && sleep 1 && echo listen" --upload.githubAppToken=${{ secrets.LHCI_GITHUB_APP_TOKEN }}
